server:
  port: 8189
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
