rootProject.name = "otus-homeworks"
include("lesson4-reflection")
include("lesson6-unittests")
include("lesson8-stream-api")
include("lesson11-multithreading")
include("lesson15-patterns1")
include("lesson16-patterns2")
include("lesson19-db-interaction")
include("lesson22-web-server")
include("lesson23-spring-context")
include("lesson24-spring-boot")
include("lesson26-hibernate2")
